on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure cmake
        run: cmake -B build -G "Visual Studio 16 2019"
      - name: Build and package msi with cmake
        run: cmake --build build --config RelWithDebInfo --target PACKAGE
      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: build
          overwrite: true

        

