name: Build

on:
  push:
    branches:
      'master'
    tags:
      '[0-9]+\.[0-9]+\.[0-9]+.*'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'license.txt'
      - '**/*.md'
      - '.github/**/*'
  workflow_dispatch:

jobs:
  build:
    name: Build binary and create MSI
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure cmake
        run: cmake -B build -G "Visual Studio 16 2019"
      - name: Build and package msi with cmake
        run: |
          # Since we run on windows, use powershell syntax
          echo "$($env:GITHUB_REF)" > build/github-ref
          echo "$($env:GITHUB_SHA)" > build/commithash
          cmake --build build --config RelWithDebInfo --target PACKAGE
      - name: Build nupkg
        run: choco pack --outputdirectory build build\install\chocolatey\hobocopy.nuspec
      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hobocopy
          path: build
          overwrite: true
  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: [build]
    name: Call
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      artifact-id: hobocopy
